name: Build and Upload Release Assets

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime: [win-x86, win-x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish self-contained single file for ${{ matrix.runtime }}
        run: |
          dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained true \
            -p:PublishSingleFile=true \
            -p:IncludeNativeLibrariesForSelfExtract=true \
            -p:EnableCompressionInSingleFile=true \
            -p:Version=${{ github.event.release.tag_name }} \
            -o ./publish/${{ matrix.runtime }}

      - name: Zip published output for ${{ matrix.runtime }}
        run: |
          cd publish/${{ matrix.runtime }}
          zip -r ../../myapp-${{ matrix.runtime }}-${{ github.event.release.tag_name }}.zip .

      - name: Upload Releases
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./myapp-${{ matrix.runtime }}-${{ github.event.release.tag_name }}.zip
          draft: true
          prerelease: ${{ steps.pre.outputs.is_prerelease }}
